googleapis/librarian

.github/workflows/generator.yaml, all_test.go, cmd/generator/main.go, go.mod
Initiate github.com/googleapis/generator as a Go module, and introduce
the initial CI builds to support Go development.
=> ci: add initial builds for Go development

containers/dotnet/Dockerfile, containers/dotnet/MakeItSo/ApiCatalog.cs, containers/dotnet/MakeItSo/ApiMetadata.cs, containers/dotnet/MakeItSo/CreateCommand.cs, containers/dotnet/MakeItSo/ICommand.cs, containers/dotnet/MakeItSo/MakeItSo.csproj, containers/dotnet/MakeItSo/Program.cs, containers/dotnet/MakeItSo/UpdateCommand.cs
Copied container from
https://github.com/jskeet/google-cloud-dotnet/tree/docker-generate/picard
=> containers/dotnet: add initial container

internal/gitrepo/gitrepo.go
It's unclear whether this is actually needed or not - I can't see how the "default" is actually defaulting otherwise, but I may be missing something.
=> impl(internal/gitrepo): clone recursively (include submodules)

internal/generate/create.go, internal/generate/flags.go, internal/generate/generate.go, internal/generate/run.go
Create a framework that supports multiple command options, each with different flags and functionality.
To see this in action, run:
```
go run ./cmd/generator -help
go run ./cmd/generator generate -help
go run ./cmd/generator create -help
```
=> impl(internal/generate): add framework for flags

internal/generate/create.go, internal/generate/flags.go, internal/generate/generate.go, internal/generate/run.go
The top-level command is not like the others. Refactor the construction of the top-level command and remove unnecessary fields from the command struct.
Fixes #20
=> impl(internal/generate): refactor generatorCommand

Dockerfile
This is aimed at running the CLI from Cloud Run and similar platforms.
=> feat: Add an initial Dockerfile to run the CLI

internal/command/command.go
Without this change, the CLI is defaulting to an incorrect path for the /tmp repo checkout.
=> fix: use default googleapis checkout when arg not provided

internal/container/container.go
As seen in https://github.com/googleapis/google-cloud-dotnet/blob/ffc678a023abc9da786ed9ce3f10615d42f01ac1/tools/Google.Cloud.Tools.ReleaseManager/ContainerCommand.cs#L44, there is no longer an update command.
Resolves `Configuration error: Unknown subcommand '--command=update'`
Note also the removal of `--commmand=`, as the container is looking for a command in arg[0] rather than processing flags as shown here: https://github.com/googleapis/google-cloud-dotnet/blob/ffc678a023abc9da786ed9ce3f10615d42f01ac1/tools/Google.Cloud.Tools.ReleaseManager/ContainerCommand.cs#L47-L53
=> fix: use 'generate' subcommand for dotnet container

internal/command/clone.go, internal/command/command.go
This also refactors our temporary directories so they're under one directory per CLI run, e. g. /tmp/generator-20241212T153039.
Fixes #40.
=> feat: Perform defensive copying

internal/command/command.go, internal/command/flags.go, internal/container/container.go
This workflow is for "unconfigured generation, based only on the API definition". (This is only unconfigured in terms of any language-specific configuration which would live in generator-input; we'd still expect a service config etc.)
The new "build" flag says whether or not to attempt to build the result.
Currently only a single language is supported; we could potentially iterate over multiple specified languages instead.
When building "unconfigured" code, we pass "--generator-output" to the container, instead of "--repo-root", to indicate the nature of the code to be built.
=> feat: Implement the "generate" workflow

internal/command/command.go
e.g. `export GENERATOR_CLI_REPOSITORY=us-docker.pkg.dev/my-project/my-repo`
Fixes #54
(Note that if an image is specified via `-image`, that's assume to be definitive.)
=> feat: Allow a default repository to be specified via an environment variable

go.mod
Resolves
https://fusion2.corp.google.com/invocations/8bc4fbf4-1d35-4821-ae0c-0715b994533b/targets/cloud-devrel%2Fclient-libraries%2Fcloud-sdk-production-pipeline%2Fcontinuous;config=default/log
=> fix: go.mod declares 1.23 (no longer 1.23.0)

internal/command/command.go
=> fix: Clean non-API-specific files when configuring a new API

internal/command/command.go, internal/container/container.go, internal/gitrepo/gitrepo.go
Resolves #69
Example build: https://fusion2.corp.google.com/invocations/ef4a832b-54f1-4dd7-9778-46f08539eee5/targets/cloud-devrel%2Fclient-libraries%2Fcloud-sdk-production-pipeline%2Fcontinuous;config=default/log
Also:
* Only throw an error in push() if push is requested.
* Minor formatting improvement ("thick line") to docker command output separators.
* Pretty-print the git status to the logs.
=> feat: implement commit

go.mod, internal/command/command.go, internal/gitrepo/gitrepo.go
We now always clone repos fully instead of with depth=1 - the latter breaks anything that uses the commit log. (We can potentially add a flag for that later.)
The change to filtering in GetApiCommits mirrors what we do in .NET; this is a much, much faster way of finding the commits that actually change directories. We don't even try to handle multi-parent commits, but I don't think that's required at the moment.
=> fix: Fix update-repo ready for further testing

.kokoro/continuous.cfg
When this is running regularly, we'd normally expect to see very few APIs change on each run - but right now there's effectively a backlog.
=> chore: Update the current .NET generation test job timeout

internal/command/commitmessage.go, internal/command/createreleasepr.go
Lots more to do here, such as:
- Including a link to the commit for each line
- Deduping (only use each commit once, and if multiple commits have the same line, have a single line and link to all the commits)
- Highlight breaking changes
- Maybe report dependency updates
This commit also fails the whole process if we fail to commit a change. (That's really fatal.) We should only "undo and continue" if *build* fails - in a later change, we should move the build to after the commit.
=> feat: Parse commit messages and format them as release notes

internal/command/command.go, internal/command/configure.go, internal/command/createreleasepr.go, internal/command/flags.go, internal/command/updateapis.go, internal/command/updateimagetag.go
This means we can still log command line arguments without accidentally logging the access token (which is sensitive).
=> feat: Use an environment variable for the GitHub access token

internal/command/updateapis.go, internal/command/updateimagetag.go, internal/gitrepo/gitrepo.go
The callers of this are really only interested in cleaning the working tree, so let's do that instead.
=> chore: Remove ResetHard from gitrepo

internal/command/commitmessage.go, internal/command/updateapis.go
Having a blank line between the first line of a commit message and the rest improves the display in some tooling, and this "title" will be more useful when looking at a repo history than "whatever the first line of the first commit happened to be".
=> feat: Add a "title" line to the commit message when updating APIs

internal/command/command.go, internal/command/createreleasepr.go, internal/command/flags.go, internal/command/release.go, internal/container/container.go, internal/gitrepo/gitrepo.go
This is currently incomplete, as it will only do the build/test/package part, not the final publication. I'd like to see this much code working (with a currently-nonexistent container implementation for .NET) before doing the final part.
=> feat: First pass at the Librarian 'release' command

internal/command/clone.go, internal/command/command.go, internal/command/configure.go, internal/command/createreleasepr.go, internal/command/flags.go, internal/command/generate.go, internal/command/release.go, internal/command/updateapis.go, internal/command/updateimagetag.go, internal/container/container.go, internal/gitrepo/gitrepo.go
We still need the context to interact with the GitHub client, but that's all.
Fixes #113
=> chore: Remove context parameter wherever possible

go.mod, internal/command/clone.go, internal/command/command.go, internal/command/configure.go, internal/command/createreleasepr.go, internal/command/generate.go, internal/command/release.go, internal/command/updateapis.go, internal/command/updateimagetag.go, internal/container/container.go, internal/librarian/librarian.go
All commands create a work-root and do language validation; many also obtain a language repo by opening/cloning. This change puts all common information into a CommandContext struct, setting it up in one place and then passing it into an execute function.
Further refactoring may be desirable for container execution, to set up the image and environment aspects within a single struct that is then passed into all the container functions.
Fixes #117.
=> refactor: Refactor command implementations to reduce duplication

internal/command/command.go, internal/command/createreleasepr.go, internal/command/flags.go
(Aside from anything else, this avoids creating a large /tmp/env-vars.txt file with the result of several runs, when testing locally!)
=> feat: Create env-vars.txt in the work-root by default

internal/command/command.go, internal/command/configure.go, internal/command/createreleasepr.go, internal/command/generate.go, internal/command/release.go, internal/command/updateapis.go, internal/command/updateimagetag.go
(I've been peeved by this split every time we've added a new command...)
I'd like to be able to express - for each flag per command - whether the flag is optional or required, but that's a bigger change, and not worth doing just yet.
=> refactor: Colocate flag initialization functions with other command data

internal/command/release.go, internal/container/container.go, internal/gitrepo/gitrepo.go
- Fix typo in "what we'd do next" message
- Fix casing of Librarian-Release-ID when finding commits
- Fix adding of commits to the list of commits to release
- Fix output subdirectory creation
=> fix: various release command fixes

.louhi/check_pr_status.go
In case someone merges PR before we the check gets invoked, it shouldn't block
=> fix: fix logic to handle PR that is already merged

internal/command/release.go
this is so kokoro does not need to check out repo as well as has the ability to point to different repo than default
=> fix: make repo-root not required and allow repo-url override for release job

internal/command/command.go, internal/command/createreleasepr.go, internal/command/flags.go, internal/command/release.go, internal/container/container.go, internal/gitrepo/gitrepo.go
This requires:
- Checking the push flag
- Publishing libraries using a new publish-library container command
- Creating releases/tags in GitHub, which requires a new flag (tag-repo-url)
=> feat: add final steps of the release command

internal/command/createreleasepr.go
This restricts the command to only releasing the specified library, and causes the command to fail if that library *isn't* then released (either because there are no changes, or potentially because there's a typo in the library name, or because the integration tests failed; at the moment it's up to the user to figure out which).
Currently this does *not* force a library to be released if it wouldn't otherwise be. We could potentially add that functionality if it proves desirable. (Otherwise users will have to create "no-op" commits that affect a path specified for the library.)
=> feat: Support library-id flag in create-release-pr

internal/command/command.go, internal/command/createreleasepr.go, internal/command/flags.go, internal/command/release.go, internal/githubrepo/githubrepo.go, internal/gitrepo/gitrepo.go
This should make it easier to keep track of what uses the GitHub API vs what's just Git.
=> refactor: Separate GitHub operations from plain Git operations

internal/command/command.go, internal/command/configure.go, internal/command/createreleasepr.go, internal/command/pullrequest.go, internal/command/updateapis.go, internal/command/updateimagetag.go, internal/githubrepo/githubrepo.go
Generation/build errors should be reported, but should not prevent other libraries from being generated.
Refactored the existing code to remove duplication.
=> feat: Handle update-apis in the same way as configure/create-release-pr

internal/command/pullrequest.go
The log may be very large; having a line-per-error summary at the bottom is handy.
=> chore: restate errors in the log when a PR is not going to be created

internal/command/createreleaseartifacts.go, internal/command/createreleasepr.go, internal/command/flags.go
This must be set to a bug number (although we only validate that it starts with b/) and can be specified in create-release-pr and create-release-artifacts.
This commit removes the -skip-build flag; I believe we *always* want to build when creating a release PR. (Whether we run unit tests or not is potentially separate.)
=> feat: Add -skip-integration-tests flag

internal/command/commitmessage.go, internal/command/createreleasepr.go
Additionally, bug fixes for:
- Redundant blank lines before the metadata in release notes
- The conventional commit type of "fix" instead of "fixes"
- Failing to take account of Go's switch/case not falling through to following cases
Fixes b/416167983 and b/416164401
=> feat: Upper-case first letter of lines in release notes

internal/command/createreleaseartifacts.go
This caught me out after manually changing a release PR, and I couldn't tell which commit was failing.
=> chore: Provide more diagnostics when checking metadata

Dockerfile
this allows us to use librarian image when running tap presubmits
=> fix: add additional packages necessary for code generation for librarian

Dockerfile, cloudbuild.yaml
note, the cloudbuild.yaml file is a placeholder for when we onboard to AR exit gates
=> fix: update Docker image to match existing version in go.mod + create cloudbuild.yaml file

internal/command/mergereleasepr.go, internal/githubrepo/githubrepo.go
This now polls (once per minute) for all the conditions we want to enforce until it's ready to merge, then merges. See the comment on waitForPullRequestReadinessSingleIteration for details of the conditions that are enforced.
=> feat: Make merge-release-pr a one-stop-merging-shop

internal/command/command.go, internal/command/configure.go, internal/command/createreleaseartifacts.go, internal/command/createreleasepr.go, internal/command/pullrequest.go, internal/command/updateapis.go, internal/command/updateimagetag.go
- Use Markdown lists to represent items in PRs
- Add the Release-ID to release PR descriptions
- Format timestamps with a trailing Z for UTC
- Use conventional commit messages for release commits
=> feat: Improve PR and commit messages

internal/command/flags.go, internal/command/mergereleasepr.go
This is intended to be somewhat general-purpose, so the only URL requirement is that we can put the merged commit hash as a suffix of the supplied prefix.
=> feat: Allow merge-release-pr to wait for the merge commit to be synchronized

internal/command/mergereleasepr.go
This should be sufficient as we sync GOB every 30 second
=> chore: reduce wait time checking for GOB sync to 30 minutes

internal/command/command.go, internal/command/publishreleaseartifacts.go
Without this, we don't know what environment variables to pass in etc.
=> fix: load the pipeline config from the repo when publishing

cloudbuild-exitgate.yaml
The new file cloudbuild-exitgate.yaml is based on cloudbuild.yaml. The difference is that the new file points to images-dev repo
=> feat: add cloudbuild config for publishing image via AR Exit Gate

internal/command/command.go, internal/command/flags.go
At the moment having this validation step is an impedence to onboarding new languages. Remove the validation, until we see a reason to add it back.
=> impl(internal/command): remove validate language

internal/command/command.go, internal/command/configure.go, internal/command/createreleaseartifacts.go, internal/command/createreleasepr.go, internal/command/generate.go, internal/command/mergereleasepr.go, internal/command/publishreleaseartifacts.go, internal/command/pullrequest.go, internal/command/stateandconfig.go, internal/command/updateapis.go, internal/command/updateimagetag.go
The term context has a specific connotation in Go. See
https://go.dev/blog/context-and-structs.
CommandContext does not fit this definition, and using the variable
`ctx` in reference the variable makes it easy to confuse the two
concepts. Rename CommandContext to commandState, and unexport it, since
the struct contains only unexported fields and is not used outside the
package.
Use of the variable `ctx` to reference `commandState` exists throughout the
codebase, and will be fixed throughout upcoming PRs.
=>  impl(internal/command): rename CommandContext to commandState 

internal/command/command.go, internal/command/configure.go, internal/command/createreleaseartifacts.go, internal/command/createreleasepr.go, internal/command/generate.go, internal/command/mergereleasepr.go, internal/command/publishreleaseartifacts.go, internal/command/pullrequest.go, internal/command/stateandconfig.go, internal/command/updateapis.go, internal/command/updateimagetag.go
The term context and the variable ctx has a specific connotation in Go. See https://go.dev/blog/context-and-structs. Rename references to ctx to state.
Fixes #189
=> impl(internal/command): rename ctx to state

internal/cli/cli.go, internal/librarian/command.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Instead of having Flags and FlagFunctions as exported fields, add Command.SetFlags to handle this fields. This makes it clear that there is only one place where they should set (at init), and simplifies the Commands struct.
=> impl(internal/cli): add Command.SetFlags

internal/cli/cli.go, internal/cli/cli_test.go
There were previously no tests for internal/cli. This change adds a basic set of unit tests to cover core functionality.
A bug in Lookup is also fixed.
=> impl(internal/cli): add basic tests for package

CONTRIBUTING.md
This will want to be refined over time, but at least addresses the concern in #247 around a lack of clarity for external contributions.
Our team processes should be more thoroughly documented, which is tracked by #263 - but they need to be determined first.
=> docs: initial contributing guidelines

internal/cli/cli.go, internal/cli/version.go, internal/cli/version_test.go, internal/librarian/command.go, internal/librarian/version.go
A librarian subcommand is added which prints the binary version.
Fixes https://github.com/googleapis/librarian/issues/238
=> impl(cmd/librarian): add support for version

.github/label-sync.yml
Once this is merged, I'll remove the labels we don't want.
Part of #188
=> chore: stop syncing labels with label-sync

internal/cli/cli.go, internal/cli/cli_test.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go, internal/librarian/version.go
The librarian commands were previously undocumented. Added Usage and Long fields to the Command struct to serve as placeholders for usage text.  For now, these fields are populated with a TODO as a placeholders.
When constructing the usage information, the code will now panic if Short, Long, or Usage are empty, so that we ensure new commands are documented moving forward.
For https://github.com/googleapis/librarian/issues/237
=> feat(internal/cli): add Command.Usage and Command.Long fields

internal/cli/cli.go, internal/cli/cli_test.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/librarian.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go, internal/librarian/version.go
Rather than splitting into two fields, use a single string with the format:
[name] [short]
Examples:
- configure setups new APIs for client library
- version prints the version information
This makes it easier to read and parse in code and setups a predictable sentence structure.
Fixes https://github.com/googleapis/librarian/issues/244
=> impl(internal/librarian): consolidate command name and short

internal/librarian/createreleaseartifacts.go, internal/librarian/flags.go, internal/librarian/generate.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateimagetag.go
The usage now genuinely specifies the required flags for each command. Some of these were only implicitly being checked (in that if they weren't specified, the command would fail in a non-obvious way).
Fixes #387
Fixes #390
Fixes #391
Fixes #392
Fixes #393
=> chore(internal/librarian): tweaks to usage and flag validation

CONTRIBUTING.md
Add information to CONTRIBUTING.md explaining the convention for leaving TODOs in the codebase.
=> doc: add guidelines for writing TODOs

internal/librarian/generate.go
Update runGenerate to accept various flags as explicit parameters instead of reading from global flags. This makes the function easier to test, reuse, and reason about in isolation.
For https://github.com/googleapis/librarian/issues/492
=> fix(internal/librarian): pass arguments directly to runGenerate

all_test.go
Add a test to ensure that exported funcs, types, consts, and vars must have comments.
This test is skipped until https://github.com/googleapis/librarian/issues/521 is addressed.
For https://github.com/googleapis/librarian/issues/522
=> feat(all): check that exported symbols have doc comments

internal/cli/cli.go, internal/cli/cli_test.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/librarian.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go, internal/librarian/version.go
Change Command.Run to take a *config.Config:
Run(ctx context.Context, cfg *config.Config) error
This lets us construct the config once in librarian.Run and pass it through, instead of rebuilding it in each command.
Fixes https://github.com/googleapis/librarian/issues/575
=> feat(internal/cli,librarian): pass config to cli.Run

internal/cli/cli.go, internal/cli/cli_test.go, internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/librarian.go
The CLI framework now supports subcommands and is used to construct the top-level Librarian command. This aligns its construction with other commands and makes it possible for other subcommands to be supported in the future.
Fixes https://github.com/googleapis/librarian/issues/469
=> feat(internal/cli,librarian): use cli framework for Librarian

all_test.go
=> fix(all_test.go): make the linter recognize type doc comments

internal/docker/docker.go, internal/docker/docker_test.go
A Docker.run method is added to encapsulate Docker command execution. This isolates command construction, making it easier to test.
A test is also added for Docker command construction across all supported operations, using a mock run method that compares the expected and actual docker command.
The test surfaced a bug in PublishLibrary, where the --version flag was incorrectly set to the library ID instead of the library version. This has been fixed.
Fixes https://github.com/googleapis/librarian/issues/592
=> feat(internal/docker): add Docker.run and test command construction

internal/librarian/command.go, internal/librarian/configure.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/pullrequest.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Remove `context.Context` from the `commandState` struct and instead passes it explicitly to functions that require it, following the guidance from https://go.dev/blog/context-and-structs.
This refactor improves clarity and avoids storing context across method boundaries.
Fixes #516
=> fix(internal/librarian): remove ctx from commandState

internal/cli/cli.go, internal/cli/cli_test.go, internal/librarian/command_test.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/librarian.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go, internal/librarian/version.go
Usage is often used to refer to `flag.Flags.Usage()`, and we use it when referring to `Command.Flags.Usage()`.
Rename to `UsageLine`, which align with the terminology used by `cmd/go`:
https://pkg.go.dev/cmd/go/internal/base#Command.UsageLine.
Fixes https://github.com/googleapis/librarian/issues/613
=> fix(internal/cli): rename Usage to UsageLine

internal/secrets/secrets.go
Creates a simple secrets module that implements a `secrets.Get` function
Towards #531
=> feat(internal/secrets): introduce secrets package

internal/config/config.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/flags.go, internal/librarian/generate.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Move the `LIBRARIAN_REPOSITORY` environment variable to the `config` package.
Fixes: #509
=> chore(internal/config): move `LIBRARIAN_REPOSITORY` to config package

internal/gitrepo/gitrepo.go, internal/librarian/flags.go
Refactors how default values for the Git user name and email are handled. The responsibility for setting defaults is moved from downstream code into the initial flag parsing logic.
The default values are now set in the flag definitions within the `config` package. This ensures that `Config.GitUserName` and `Config.GitUserEmail` are always populated, making the `config` struct the single source of truth.
Fixes #624
=> refactor(internal/gitrepo): move defaultUserName and defaultUserEmail to config

internal/docker/docker.go
Remove check for empty string and add the `library-id` flag unconditionally.
Fixes #630
=> fix(internal/docker): clean method to unconditionally add the library-id flag

.golangci.yaml, all_test.go
Configure golangci-lint to run as part of `go test ./...`.
Remove TestStaticcheck, TestVet, and TestUnparam, as these are now covered by golangci-lint. Disable linters that cause test failures, which will be adjusted as a follow-up.
For https://github.com/googleapis/librarian/issues/638
=> fix(all): set up golangci-lint

internal/config/config.go, internal/docker/docker.go, internal/docker/docker_test.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
These two env variables, `KOKORO_HOST_ROOT_DIR` and `KOKORO_ROOT_DIR`, are used in `docker` package. Therefore, these two variables can't be converted to flags because all functions in `flags.go` are package private.
These variables are already part of `config` package, but there will be breaking changes in `docker` package. For example, we need to pass `*config.Config` to all public functions in `docker/docker.go`.
Fixes #507
=> feat(internal/docker): pass config to public functions in docker.go

internal/github/github.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/mergereleasepr.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/pullrequest.go, internal/librarian/stateandconfig.go
Add type and constant alias in githubrepo package to remove all uses of github.com/google/go-github/v69/github types and constants.
Rename the githubrepo package to github, since this package provides operations on the GitHub API. This also avoids confusion with the gitrepo package, which provides git operations on repositories.
Fixes #626
=> fix(internal/github): rename githubrepo to github

internal/docker/docker.go
Remove validations in public functions in `docker.go` since we assume the input are valid.
Fixes #622
=> chore(internal/docker): remove validation in `docker.go`

internal/config/config.go, internal/config/config_test.go, internal/docker/docker.go, internal/docker/docker_test.go, internal/librarian/command.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/generate.go, internal/librarian/librarian.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Moves the call to user.Current into the config package, keep Docker-related logic focused.
Fixes #590
=> refactor(internal): move user lookup to config

.golangci.yaml
misspell finds commonly misspelled English words.
For https://github.com/googleapis/librarian/issues/638
=> chore(golangci-lint): enable misspell

internal/config/config.go, internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/configure.go, internal/librarian/createreleaseartifacts.go, internal/librarian/createreleasepr.go, internal/librarian/flags.go, internal/librarian/generate.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go, internal/librarian/url.go, internal/librarian/url_test.go
Simplify the CLI by merging the redundant -repo-root and -repo-url flags into a single -repo flag.
Previously, users had to choose between two different flags to specify the repository context.
The new -repo flag accepts either a local filesystem path or a remote Git URL. The CLI will now automatically detect the input type and handle it accordingly.
Fixes #611
=> refactor(internal/librarian): merge -repo-root and -repo-url into a single -repo flag

internal/librarian/librarian.go
Remove update-apis command, because it is no longer needed.
Keep the unused backend code, because most of it will be used in the new generate command.
Fix: #674
=> chore(internal/librarian): remove update-apis command

internal/config/config.go, internal/librarian/configure.go, internal/librarian/flags.go, internal/librarian/generate.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Rename config.APIRoot to config.Source and flagAddAPIRoot to flagAddSource to match the flag name.
Fixes https://github.com/googleapis/librarian/issues/677
=> fix(internal/config,internal/librarian): rename APIRoot to Source

internal/config/config.go, internal/librarian/configure.go, internal/librarian/flags.go, internal/librarian/generate.go
Rename APIPath to API to match the new flag name.
For https://github.com/googleapis/librarian/pull/686
=> fix(internal/config): rename APIPath to API

internal/librarian/createreleasepr.go, internal/librarian/flags.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Remove the flag push according to go/librarian:cli-reimagined.
The config is not touched and will get false by default. Underlying logic will change in future, leaving out of scope for this fix.
Fixes #679
=> fix(internal/librarian): remove flag push

internal/config/config.go, internal/config/config_test.go, internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/createreleasepr.go, internal/librarian/flags.go, internal/librarian/updateapis.go, internal/librarian/updateimagetag.go
Combine git-user-name and git-user-email flags into push-config flag.
Fixes #678
=> refactor(internal): combine git-user-name and git-user-email flags

all_test.go
Add a test to verify that all code is properly formatted with gofmt.
Fixes https://github.com/googleapis/librarian/issues/738
=> fix(all): add TestGoFmt

internal/docker/docker.go, internal/docker/docker_test.go, internal/librarian/createreleaseartifacts.go, internal/librarian/generate.go, internal/librarian/publishreleaseartifacts.go, internal/librarian/updateimagetag.go
Also removed network access limitations and renamed command to their documented names in go/librarian:cli-reimagined
Fixes: #806
=> refactor(internal/docker): rm commands not used for generate CLI cmd and rm network access limitations

internal/librarian/generate.go, internal/librarian/generate_test.go, internal/librarian/stateandconfig.go
State file is now expected in `.librarian/state.yaml`
Fixes #916
=> fix(internal/librarian): load state.yaml from librarian dir

internal/github/github.go, internal/github/github_test.go, internal/librarian/command.go, internal/librarian/generate.go, internal/librarian/generate_test.go, internal/librarian/librarian.go, internal/librarian/librarian_test.go
Just a little clean up, renaming all instances of CamelCase `Url` to upper case `URL`
Fixes #689
=> chore(internal): fix Url to URL casing

.github/multi_approvers.yaml, .github/workflows/multi_approvers.yaml
Migrating from https://github.com/googleapis/infra-github/blob/main/.github/workflows/multi_approvers.yaml so that we can get rid of that repo entirely.
=> chore: migrate multi-approvers workflow to Librarian repo

.github/workflows/multi_approvers.yaml
When a PR is initiated from a fork, GitHub actions that are triggered based on `pull_request_review` do not receive the needed secrets. So, multi-approvers can't work. Additionally, for non-fork PRs, multi-approvers will already be green anyway because all users with permission to create branches are Googlers. So, the `pull_request_review` trigger is useless.
=> chore: remove pull_request_review trigger from multi_approvers.yaml

internal/github/github.go, internal/github/github_test.go, internal/librarian/command_test.go
Derive Github url only from the remote named origin. The other remotes will be ignored.
Fix #919
=> fix(internal/github): derive github url from remote origin

internal/github/github.go
Add https scheme in error message, because we limit git to use https urls.
Fixes #993
=> fix(internal/github): add github remote https limitation in error message

internal/librarian/generate.go, internal/librarian/generate_test.go
=> fix(internal/librarian): populate service config in `configure` command

internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/flags.go, internal/librarian/generate.go, internal/librarian/generate_test.go
Make repo flag optional, removing required flag validation. Add logic to derive from current working directory when there is librarian state file detected, otherwise, return error.
Fixes: #1516
=> fix(internal/librarian): make repo flag optional and derive from cwd when applicable

internal/sidekick/internal/config/gcloudyaml/gcloud_test.go
TestGcloudConfig is skipped in https://github.com/googleapis/librarian/pull/1533. The test failure is now fixed.
Fixes https://github.com/googleapis/librarian/issues/1544
=> fix(internal/config/gcloudyaml): fix TestGcloudConfig

.github/workflows/librarian.yaml, all_test.go, internal/gitrepo/gitrepo.go, internal/librarian/flags.go, internal/librarian/mocks_test.go, internal/librarian/state.go
Add TestGoImports to ensure all Go files are formatted according to `goimports`.
The new test runs `goimports -d` and fails the build if there is a diff. This ensures all committed code is correctly formatted.
As part of this change, existing files have been formatted with `goimports -w`.
Fixes https://github.com/googleapis/librarian/issues/1529
=> test: enforce goimports formatting

internal/sidekick/internal/config/config.go, internal/sidekick/internal/config/config_test.go, internal/sidekick/refreshall.go, internal/sidekick/refreshall_test.go
=> fix(sidekick): ignored directories are configurable

.golangci.yaml, internal/sidekick/downloads_cache_test.go, internal/sidekick/internal/api/dependencies_test.go, internal/sidekick/internal/api/documentation.go, internal/sidekick/internal/api/model.go, internal/sidekick/internal/dart/annotate.go, internal/sidekick/internal/dart/annotate_test.go, internal/sidekick/internal/dart/dart.go, internal/sidekick/internal/dart/generate.go, internal/sidekick/internal/golang/golang.go, internal/sidekick/internal/golang/gotemplate.go, internal/sidekick/internal/golang/gotemplate_test.go, internal/sidekick/internal/parser/pagination.go, internal/sidekick/internal/parser/service_config.go, internal/sidekick/internal/rust/annotate.go, internal/sidekick/internal/rust/codec.go, internal/sidekick/sidekick_dart_test.go, internal/sidekick/sidekick_rust_prost_convert_test.go, internal/sidekick/sidekick_rust_prost_test.go, internal/sidekick/sidekick_sample_test.go, internal/sidekick/sidekick_test.go, internal/sidekick/update_test.go
Fix these errors detected by TestGolangCILint:
```
--- FAIL: TestGolangCILint (1.53s)
all_test.go:156: /Users/julieqiu/bin/homebrew/Cellar/go/1.24.4/libexec/bin/go run github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest run: exit status 1
internal/sidekick/internal/api/model.go:27:2: Comment should end in a period (godot)
// descriptorpb.FieldDescriptorProto_Type
^
internal/sidekick/internal/api/model.go:290:1: Comment should end in a period (godot)
// ```
^
internal/sidekick/internal/api/model.go:368:1: Comment should end in a period (godot)
// OperationInfo contains normalized long running operation info
^
internal/sidekick/internal/api/documentation.go:116:9: QF1004: could use strings.ReplaceAll instead (staticcheck)
new := strings.Replace(*documentation, override.Match, …
=> fix(golangci-lint): fix errors in internal/sidekick

generate_e2e_test.go, internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/generate.go, internal/librarian/generate_test.go
Set api-source value to https://github.com/googleapis/googleapis when the flag is unspecified.
Also clone googleapis repo. 
fix: https://github.com/googleapis/librarian/issues/1512
=> feat: clone googleapis if apisource is unspecified

internal/sidekick/internal/config/source_roots_test.go
=> test(sidekick): missing tests for `config` package

internal/sidekick/internal/config/config.go, internal/sidekick/internal/config/config_test.go
=> test(sidekick): missing `config` tests

codecov.yml
Fixes #1543 - `internal/sidekick` is at 83.31% coverage. Most of the untested code is error handling.
=> test(sidekick): enable codecov

infra/test/token-access-test.yaml
The librarian repository is checked out as /workspace. There's no
/workspace/librarian folder.
=> ci: fixing missing 'workspace/librarian' error

internal/librarian/generate.go, internal/librarian/state.go, internal/librarian/state_test.go
The release code will also need to use some of this functionality and to make the code easier to call/read I refactored out the idea of a content loader that I believe was added to help coverage. I am fine taking a couple points of a coverage hit to make the code, in my opinion, more readable.
Updates: #1009
=> refactor(internal/librarian): remove contentLoader

internal/github/github.go, internal/github/github_test.go
We are going to need more github functionality in order to tag and release from librarian. This adds all of the functions that should be required.
Updates: #1009
=> feat(internal/github): add support requred for release

internal/config/config.go, internal/config/config_test.go, internal/librarian/flags.go, internal/librarian/librarian.go, internal/librarian/release.go, internal/librarian/tag_and_release.go, internal/librarian/tag_and_release_test.go
Also added the one new flag we will need for this command.
Updates: #1009
=> feat(internal/librarian): add skeleton for release tag-and-release

all_test.go
I must have forgot to revert removing this in #1662. Currently this check is not being enforced.
Found reviewing: #1686
=> test: restore len check for goimports

infra/prod/generate-worker.yaml, infra/prod/generate.yaml, internal/automation/cli.go, internal/automation/cli_test.go, internal/automation/trigger.go, internal/automation/trigger_test.go
The Cloud Build generate-worker job to pass the _PUSH substitution variable to the next Cloud Build jobs. They invoke Librarian CLI with either '-push=true' or '-push=false' parameter. This controls whether the job creates a pull request or not.
This change should come with the Terraform change cl/795539979.
=> ci: Cloud Build jobs to propagate _PUSH substitution variable

internal/github/github.go, internal/gitrepo/gitrepo.go, internal/gitrepo/gitrepo_test.go, internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/generate.go, internal/librarian/mocks_test.go
Fixes #1762
Introduces a new `GitUser` struct which represents all potential configuration data needed for git operations (username/password for auth, name/email for commit messages). This is stored on the LocalRepository when it is loaded or cloned. Currently, we only allow CLI-based configuration for the password (GitHub token) -- other values are hard-coded, but we could easily pipe through arguments from the command line if needed.
=> feat: add ability to create branch and push to remote repository

infra/prod/stage-release-worker.yaml
Let's propagate the _PUSH substitution variable when we run stage-release job. The corresponding change in Terraform is at cl/798304040.
=> ci: push option to stage-release-dispatcher

cloudbuild-exitgate-deprecated.yaml
This additionally deprecates old AR exit gate cloud build file
=> chore: migrate librarian to publish to new cloud-sdk-librarian-prod GCP project

infra/prod/stage-release.yaml
I believe this wasn't treating "init" as a separate command, so made it its own argument
=> fix: release init command invocation

internal/librarian/generate.go
An alternative would be to clean the output directory after each library is generated, but keeping them all (separately) will make it easier to diagnose problems.
Fixes #1774
=> fix: use a clean output directory for each API when generating

internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/release_init.go, internal/librarian/release_init_test.go
We should intentionally copy over only the files that are in the output directory of the release init container. We don't mandate today that all libraries files must be copied over, so we should selectively overwrite files when required.
Fixes: #1806
=> fix(internal/librarian): don't clean dir for release init copies

internal/librarian/release_init.go, internal/librarian/release_init_test.go
Also refactored the function a little as it takes a pointer to data so no need to return the data -- mutate it instead.
Fixes: #1830
=> fix(librarian): bump version while updating libraries for release

infra/prod/stage-release.yaml
Remove unnecessary step to fetch googleapis.  We don't need it for release
=> fix: remove invalid api-source flag from release init command

internal/automation/trigger.go, internal/automation/trigger_test.go, internal/github/github.go, internal/github/github_test.go
add MergeCommitSHA check, _PR substitution, PR limit in publish-release automation command
https://github.com/googleapis/librarian/issues/1786
https://github.com/googleapis/librarian/issues/1810
=> fix: add MergeCommitSHA check, _PR substitution, PR limit in publish-release automation command

internal/librarian/command.go, internal/librarian/command_test.go
It is expected behavior to defaults to the `source_roots` as documented. Adding missed implementation.
https://github.com/googleapis/librarian/blob/8f409cc46adc7958a9393e52bd4b272ce2d75697/internal/config/state.go#L116-L119
Fixes #1739
=> fix(internal/librarian): default to source_roots when no remove_regex

internal/librarian/state.go, internal/librarian/state_test.go
This allows libraries from "just protos" to be represented.
Fixes #1712.
=> feat(librarian): allow APIs to have no service config

internal/librarian/generate.go, internal/librarian/generate_test.go, internal/librarian/mocks_test.go, internal/librarian/release_please_lite.go
Function `updateChangesSinceLastGeneration` may not be needed since we don't need to pass api changes to language container.
Fixes #1866
=> fix: get conventional commits from source repository

codecov.yml, internal/sidekick/internal/api/apitest/apitest.go, internal/sidekick/internal/parser/openapi_test.go, internal/sidekick/internal/parser/parser_test.go, internal/sidekick/internal/parser/protobuf_mixin_test.go, internal/sidekick/internal/parser/protobuf_test.go
To implement discovery doc parsing I am going to need a new package
that `parser` will depend on and also needs the `Check*()` helpers.
Part of the work for #1850
=> refactor(sidekick): move test helpers

internal/sidekick/internal/parser/discovery/discovery.go, internal/sidekick/internal/parser/discovery/discovery_test.go, internal/sidekick/internal/parser/discovery/methods.go, internal/sidekick/internal/parser/discovery/methods_test.go, internal/sidekick/internal/parser/discovery/services.go, internal/sidekick/internal/parser/discovery/services_test.go
Add methods (with many details missing) to the services created from a
discovery doc.
Part of the work for #1850
=> impl(sidekick): create skeleton for methods

internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/generate.go, internal/librarian/release_init.go
Refactor `commitAndPush` function so that it can be used to create generate and release pull requests.
Updates #1703
Updates #1899
=> chore: refactor `commitAndPush` func

infra/prod/generate.yaml, infra/prod/stage-release.yaml
The branch option helps us to test the Librarian's generate and
stage-release behavior without touching the main branch of the SDK
repository.
The flag has been added in https://github.com/googleapis/librarian/pull/1893.
Let's use the flag in the Cloud Builds YAML files.
By default, "main" is passed to the variable (cl/802643045).
I have to wait for the librarian container image update so that the CLI interprets the `-push` option.
=> ci: use '-branch' option in Cloud Builds

internal/librarian/command.go, internal/librarian/generate.go, internal/librarian/generate_test.go, internal/librarian/librarian_test.go, internal/librarian/release_init.go, internal/librarian/tag_and_release.go
This PR refactors `newCommandRunner` in `command.go` to accept `GitHubClientFactory` and `ContainerClientFactory` as arguments, improving testability by enabling direct injection of mock clients.
Key changes include:
*   Defined `GitHubClientFactory` and `ContainerClientFactory` types in `command.go`.
*   Updated `newCommandRunner` to use these factories, with default implementations if `nil` is passed.
*   Modified callers of `newCommandRunner` (e.g., in `generate.go`, `release_init.go`, `tag_and_release.go`) to pass `nil, nil` for the new factory arguments to retain default behavior.
*   Added `TestGenerate_DefaultBehavior` to `librarian_test.go` to test the default `librarian generate` execution. This test utilizes the new factory arguments in `newGenerateRunner` to inject mock …
=> refactor(librarian): Inject client factories and add test for generate default

internal/librarian/command.go, internal/librarian/generate.go, internal/librarian/generate_test.go, internal/librarian/librarian_test.go, internal/librarian/release_init.go, internal/librarian/tag_and_release.go
The time to run all unit tests increases from 1 mins to 5 mins.
Example logs:
[Before](https://github.com/googleapis/librarian/actions/runs/17449743710/job/49552035801)
[After](https://github.com/googleapis/librarian/actions/runs/17449910373/job/49552495491)
Reverts googleapis/librarian#1918
=> chore: revert "refactor(librarian): Inject client factories and add test for generate default"

internal/github/github.go, internal/github/github_test.go
Fixes https://github.com/googleapis/librarian/issues/540.
This follows the pagination style in https://github.com/google/go-github?tab=readme-ov-file#pagination.
=> chore: GetLabels to paginate the GitHub responses

internal/librarian/command.go, internal/librarian/command_test.go
In case the remove-regex contains a directory that exists in .librarian/generator-input, the librarian CLI should not delete it when calling clean.
fixes: #1925
=> fix: do not delete any files in .librarian/generator-input directory

internal/sidekick/internal/rust/annotate.go
At least that is how you spell it in the `.repo-metadata.json` files.
=> fix(sidekick/rust): `GA` is spelled `stable`

internal/librarian/release_init.go
The 'release init' command was incorrectly creating a nested 'output' subdirectory within the path provided by the --output flag (aliased to WorkRoot). This caused the container's /output volume to be mounted to <workroot>/output instead of <workroot>.
This commit changes the behavior to use the r.workRoot value directly as the source for the /output volume mount, aligning with user expectations for the --output flag.
Fixes #2014
=> fix(release): use --output path directly for container mount

internal/sidekick/internal/rust_release/bump_versions.go, internal/sidekick/internal/rust_release/bump_versions_test.go, internal/sidekick/rust_bump_versions.go, internal/sidekick/rust_bump_versions_test.go, internal/sidekick/sidekick_test.go
Moving the implementation of `rustBumpVersions()` will make it easier to
share test code. I will need helpers to simulate a git repository and
I would rather keep those in a single package.
Part of the work for #2127
=> refactor(sidekick): move `rustBumpVersions()`

doc/howwewritego.md
Match the example under `Table-driven tests` with the guidelines under `Use cmp.Diff for comparisons`.
=> doc: fix typo in example in howwewritego.md

internal/librarian/command.go, internal/librarian/flags.go, internal/librarian/generate_test.go
Rather than checking if `config.APISource` is empty inside `newCommandRunner` and then setting a default, assign the default when the `api-source` flag is parsed.
=> refactor(internal/librarian): set default for api-source flag

internal/librarian/tag_and_release.go, internal/librarian/tag_and_release_test.go
Remove tagAndReleaseRunner.cfg and add `pullRequest` as a field to tagAndReleaseRunner. It is the only value used from Config.
=> refactor(librarian): remove cfg field from tagAndReleaseRunner

internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/generate.go, internal/librarian/release_init.go
Remove commitInfo.cfg and inline the individual fields to reduce coupling and only pass values through that are actually used.
=> refactor(internal/librarian): remove cfg field from commitInfo

internal/cli/cli.go, internal/cli/cli_test.go
Rewrite LookupCommand iteratively by replace recursive calls with a for loop.
Additionally, update tests to expect nil for empty remaining arguments, and merge the lookup function logic directly into LookupCommand.
=> refactor(internal/cli): rewrite LookupCommand iteratively

internal/cli/cli.go, internal/cli/cli_test.go, internal/config/config.go, internal/librarian/action_test.go, internal/librarian/generate.go, internal/librarian/librarian.go, internal/librarian/librarian_test.go, internal/librarian/release_init.go, internal/librarian/tag_and_release.go, internal/librarian/version.go
Move command execution logic from librarian.Run to a generic cli.Run
method.
Change the Command.Run field from:
```
Run func(ctx context.Context, cfg *config.Config) error
```
to
```
Action func(context.Context, *Command) error
```
This give the command handler access to the full Command context, rather
than just the config.
In a follow up PR, cli.Command will be refactored further to remove
business logic from Config out of the internal/cli framework.
=> refactor(internal/cli,librarian): move Run to cli package

internal/sidekick/internal/rust_release/bump_versions.go, internal/sidekick/internal/rust_release/bump_versions_test.go, internal/sidekick/internal/rust_release/update_manifest.go, internal/sidekick/internal/rust_release/update_manifest_test.go
I decided not to use `release-plz`. Until we are using conventional commits for
the generated libraries it produces bad results.
Part of the work for #2127
=> impl(sidekick): change `Cargo.toml` files

internal/automation/trigger.go, internal/github/github.go, internal/github/github_test.go, internal/librarian/command.go
NewClient and newClientWithHTTP previously always returned nil as an error. Remove error as a return value to simplify the API and remove unnecessary error handling throughout the codebase.
=> refactor(internal/github): remove error returns from NewClient

internal/librarian/release_init.go, internal/librarian/release_init_test.go
Fixes: https://github.com/googleapis/librarian/issues/1971
=> fix: Skip release if there are no releasable units

internal/sidekick/internal/dart/templates/lib/service.mustache
Dart classes are, by default, also interfaces. This means that adding a new method to a class will break any code that implements it.
The most conservative approach is to make the class `final` - we can relax that restriction and make it `base` later, if it makes sense.
=> feat: Make the Dart class representing the service `final`

infra/dispatcher/Dockerfile, infra/prod/generate-worker.yaml, infra/prod/publish-release-worker.yaml, infra/prod/stage-release-worker.yaml
Also pins the dispatcher image to the current version. We will need to update the command args when the new image is built.
Locally, the image size goes from 2.2Gb -> 900Mb
Towards #2142
=> build: build go binary for automation command

infra/prod/generate-worker.yaml, infra/prod/publish-release-worker.yaml, infra/prod/stage-release-worker.yaml
Towards #2142
The new entrypoint is the pre-built go binary which replaces `go run ./cmd/automation`
=> build: dispatcher uses latest image and updates command args

infra/prod/generate.yaml
To support the onboarding of additional libraries in mono repo
=> chore: increase timeout for librarian generate jobs to 2 hours

internal/sidekick/internal/api/model.go, internal/sidekick/internal/api/mustache_helpers_test.go, internal/sidekick/internal/rust/generate_test.go, internal/sidekick/internal/rust/templates/common/message.mustache, internal/sidekick/internal/rust/templates/common/model/debug.mustache, internal/sidekick/internal/rust/templates/common/model/debug/message.mustache, internal/sidekick/internal/rust/templates/common/model/deserialize.mustache, internal/sidekick/internal/rust/templates/common/model/deserialize/message.mustache, internal/sidekick/internal/rust/templates/common/model/serialize.mustache, internal/sidekick/internal/rust/templates/common/model/serialize/message.mustache, internal/sidekick/internal/rust/templates/crate/src/model/debug.rs.mustache, internal/sidekick/internal/rust/templates/crate/src/model/deserialize.rs.mustache, internal/sidekick/internal/rust/templates/crate/src/model/serialize.rs.mustache, internal/sidekick/internal/rust/templates/grpc-client/model/debug.rs.mustache, internal/sidekick/internal/rust/templates/grpc-client/model/deserialize.rs.mustache, internal/sidekick/internal/rust/templates/grpc-client/model/serialize.rs.mustache, internal/sidekick/internal/rust/templates/http-client/model/debug.rs.mustache, internal/sidekick/internal/rust/templates/http-client/model/deserialize.rs.mustache, internal/sidekick/internal/rust/templates/http-client/model/serialize.rs.mustache, internal/sidekick/internal/rust/templates/mod/debug.rs.mustache, internal/sidekick/internal/rust/templates/mod/deserialize.rs.mustache, internal/sidekick/internal/rust/templates/mod/mod.rs.mustache, internal/sidekick/internal/rust/templates/mod/serialize.rs.mustache, internal/sidekick/internal/rust/templates/nosvc/src/model/debug.rs.mustache, internal/sidekick/internal/rust/templates/nosvc/src/model/deserialize.rs.mustache, internal/sidekick/internal/rust/templates/nosvc/src/model/serialize.rs.mustache
In Rust, the documentation browser shows the code, and this code was
getting too large to render effectively. For some crates, the module is
also too large for some IDE defaults.
Motivated by https://github.com/googleapis/google-cloud-rust/issues/2550
=> feat(sidekick): split `model.rs` into modules

internal/librarian/help.go, internal/librarian/release_init.go, internal/librarian/release_init_test.go
Fixes: https://github.com/googleapis/librarian/issues/2032
Changes:
- Split updateLibrary's GetCommits functionality into a separate function for easier testing (inject commits directly without having to setup a repo)
Logic:
If a library is specified for release, force a release for it. Use the library version override if provided as the new version. If the override is not specified, report an error back to the user to use the version flag.
=> feat: Force release for a specific library even if there are no releasable changes

internal/sidekick/internal/dart/annotate.go, internal/sidekick/internal/dart/annotate_test.go, internal/sidekick/internal/dart/dart_test.go
The key of `annotateModel.imports` is not used so make the value a key and make the value a bool (as is Golang style for sets).
=> refactor: Change `annotateModel.imports` into a set

doc/config-schema.md, internal/config/librarian_config.go, internal/librarian/generate.go, internal/librarian/generate_test.go
For #897. This change implements the "generate" command part (`generate_blocked`).
When library config has generate_blocked field set to true, the generate command skips the library processing.
If the library is explicitly specified in the argument via "--library", then this Librarian CLI processes the library.
=> feat: generate_blocked field in per-library configuration

internal/sidekick/internal/rust/annotate.go, internal/sidekick/internal/rust/annotate_test.go, internal/sidekick/internal/rust/codec.go, internal/sidekick/internal/rust_release/update_sidekick_config_test.go
Note this change generates no diff on Rust generated code.
=> refactor(sidekick): Avoid passing many parameters when annotating.

doc/language-onboarding.md
Add missing link to doc/config-schema.md
=> doc: add missing link in language-onboarding.md

internal/sidekick/internal/api/test.go, internal/sidekick/internal/api/well_known_types.go, internal/sidekick/internal/dart/annotate_test.go, internal/sidekick/internal/parser/discovery/discovery.go, internal/sidekick/internal/parser/openapi.go, internal/sidekick/internal/rust/annotate.go, internal/sidekick/internal/rust/annotate_test.go, internal/sidekick/internal/rust/codec.go, internal/sidekick/internal/rust/codec_test.go, internal/sidekick/internal/rust/used_by_test.go
All the current service specifications (Protobuf, OpenAPI, Discovery)
use the same WKT (well-known types). In Protobuf the proto descriptors
of the WKT are loaded by the `import "google/protobuf/...";` directives.
In other specifications, the types need to be defined by the parser.
Likewise, in tests we need to define these types ahead of time.
Part of the work for #1850
=> cleanup(sidekick): consistent management of WKT

internal/sidekick/internal/parser/discovery/discovery.go, internal/sidekick/internal/parser/discovery/methods.go, internal/sidekick/internal/parser/discovery/methods_test.go, internal/sidekick/internal/parser/discovery/services.go, internal/sidekick/internal/parser/discovery/services_test.go
Parse the `path` field in a discovery method into the `PathInfo` field
of the `api.Method` objects.
Part of the work for #1850
=> impl(sidekick): bindings for discovery methods

internal/sidekick/internal/parser/discovery/discovery.go, internal/sidekick/internal/parser/discovery/discovery_test.go, internal/sidekick/internal/parser/discovery/sort.go
This is to preserve their order in the generated code. We want to avoid
spurious changes due to hash table salt.
Fixes #2274
=> fix(sidekick): sort discovery doc elements

internal/librarian/doc.go, internal/librarian/doc_generate.go
Added Go's versions of partials to the text template so we can recurse through nested commands and print all of thier help text godoc.
Fixes: #207
=> docs(librarian): add godoc for nested commands

internal/config/state.go, internal/librarian/state_test.go, testdata/docker/release-init-request/release-init-request.json, testdata/test-read-library-state/successful-unmarshal-libraryState.json, testdata/test-read-library-state/unmarshal-libraryState-with-error-msg.json, testdata/test-write-librarian-state/write-librarian-state-example.json, testdata/test-write-library-state/successful-marshaling-and-writing.json
`last_generated_commit` field should be omitted from all generated JSON request files: release-init-request.json, configure-request.json, generate-request.json, and build-request.json. Ref [language-onboarding.md](https://github.com/googleapis/librarian/blob/main/doc/language-onboarding.md)
Fixes #2081
=> fix(internal): skip write LastGeneratedCommit field to json

internal/sidekick/internal/parser/discovery/discovery.go, internal/sidekick/internal/parser/discovery/discovery_test.go, internal/sidekick/internal/parser/discovery/message_fields.go, internal/sidekick/internal/parser/discovery/message_fields_test.go, internal/sidekick/internal/parser/discovery/methods.go, internal/sidekick/internal/parser/discovery/methods_test.go
Parse most fields of object in a discovery doc. Fields with an inline
type definition still need some custom work.
Part of the work for #2265
=> feat(sidekick/disco): parse most object fields

internal/sidekick/internal/rust/templates/crate/src/lib.rs.mustache, internal/sidekick/internal/rust/templates/crate/src/transport.rs.mustache
- Add static INSTRUMENTATION_CLIENT_INFO to lib.rs.mustache.
- Use INSTRUMENTATION_CLIENT_INFO in transport.rs.mustache if tracing is enabled.
For #2212 see also https://github.com/googleapis/google-cloud-rust/pull/3347 and https://github.com/googleapis/google-cloud-rust/pull/3376
=> feat(sidekick): Inject InstrumentationClientInfo for tracing

internal/sidekick/internal/parser/openapi.go, internal/sidekick/internal/parser/openapi_test.go, internal/sidekick/internal/sample/api.go
That is, the messages are labeled as synthetic. And it does not change
the existing messages: only new messages are created.
Fixes #2281
=> cleanup(sidekick): OpenAPI uses synthetic mesages

internal/github/github.go, internal/gitrepo/gitrepo.go, internal/gitrepo/gitrepo_test.go, internal/librarian/command_test.go, internal/librarian/mocks_test.go, internal/librarian/release_init_test.go, internal/librarian/release_notes_test.go
We should avoid putting other packages types in APIs of our types. This breaks encapalation of the library we are trying to wrap. This package has more types like this that I will follow up with in future PRs.
Updates: #2372
=> refactor(internal/gitrepo): define a Remote type and use it

internal/sidekick/internal/parser/disco_test.go, internal/sidekick/internal/parser/discovery/discovery_test.go, internal/sidekick/internal/parser/discovery/enum_field_test.go, internal/sidekick/internal/parser/discovery/message_fields.go, internal/sidekick/internal/parser/discovery/message_fields_test.go, internal/sidekick/internal/parser/discovery/methods_test.go
=> fix(sidekick): missing IDs in discovery doc fields

cmd/librarian/doc.go, e2e_test.go, internal/automation/trigger.go, internal/config/config.go, internal/config/config_test.go, internal/librarian/flags.go, internal/librarian/help.go, internal/librarian/tag_and_release.go
This change introduces a constant for the LIBRARIAN_GITHUB_TOKEN environment variable to improve maintainability and reduce duplication.
Fixes https://github.com/googleapis/librarian/issues/2089.
=> feat(config): define LIBRARIAN_GITHUB_TOKEN as a constant

internal/sidekick/internal/rust/annotate.go, internal/sidekick/internal/rust/codec.go, internal/sidekick/internal/rust/codec_test.go, internal/sidekick/internal/rust/templates/common/enum.mustache
Change the serialization of enums for non-proto sources (discovery docs
and OpenAPI) to use strings. The main motivation to use integers in the
case of Protobuf is roundstrips where we receive an unknown enum from
a Protobuf / gRPC response, copy that to a request, and want to
serialize it without loss. That scenario is not a consideration for
OpenAPI or Discovery docs, and serializing enums as integers just does
not work.
Fixes #2406
=> feat(sidekick): enum serialization for non-proto sources

doc/library-maintainer-guide.md
This will be linked from migration issues for core/handwritten/hybrid libraries.
=> docs: first pass at a maintainer guide

doc/language-onboarding.md, internal/docker/docker.go, internal/docker/docker_test.go, internal/librarian/mocks_test.go, internal/librarian/release_init.go, internal/librarian/release_init_test.go
Fixes #2025 
Fixes #2429
Related to #2218
Skips copy of repository for `release init`. We pass the entire repo (already as read-only) to the language container.
=> fix: release init provides read-only full repository

internal/conventionalcommits/conventional_commits.go, internal/conventionalcommits/conventional_commits_test.go
The original logic expect footer to follow `key: value` (exactly one space before value) format as conventionalcommit specs. For multi-line footers, when parsing ([logic](https://github.com/googleapis/librarian/blob/9b28aa4a3619579dfa59c430afa612589b353598/internal/conventionalcommits/conventional_commits.go#L336)), the line content "Source-Link:" would fail the regex match and thus not properly recognized as footer, and gets appended to the value of the previous footer.
By relaxing the regex a bit to allow any number of spaces before "value" in footer, the multiline footer can be recognized. 
note: this format below from owlbot PR ([example](https://github.com/googleapis/google-cloud-python/commit/34a7916fa58727a01a7d32c6a1adff59a351fd54)) is technically not valid footer according to …
=> fix(internal/conventionalcommits): relax footer regex to allow line broke footers to be properly recognized

internal/sidekick/internal/rust/templates/crate/src/lib.rs.mustache, internal/sidekick/internal/rust/templates/crate/src/transport.rs.mustache
Reverts googleapis/librarian#2252
My automated testing was wrong, it was happily disabled in both the lib.rs and transport.rs because the feature flag wasn't propagated.  I have prepared a fix for the generator, but I'm finding this code incorrect and so I'd like to revert if it can be done cleanly.
=> Revert "feat(sidekick): Inject InstrumentationClientInfo for tracing"

internal/sidekick/internal/rust/annotate.go, internal/sidekick/internal/rust/annotate_test.go
This commit fixes the propagation of the `detailed-tracing-attributes` flag to all necessary annotation structs and updates the templates to correctly utilize the flag. See #2435 and #2252 
For https://github.com/googleapis/google-cloud-rust/issues/3239
Specifically:
- Adds `DetailedTracingAttributes` field to `modelAnnotations` and `serviceAnnotations` in `annotate.go` to make the flag accessible in `lib.rs.mustache` and service-level sections of `transport.rs.mustache`.
- Updates `annotateModel` and `annotateService` to populate the new fields.
- Adds comprehensive unit tests in `annotate_test.go` to verify the `DetailedTracingAttributes` flag is correctly set across `modelAnnotations`, `serviceAnnotations`, `methodAnnotation`, and `pathBindingAnnotation` based on the codec options.
- …
=> fix(sidekick/rust): Ensure detailed-tracing-attributes flag is fully propagated

internal/sidekick/internal/config/config.go, internal/sidekick/internal/config/config_test.go, internal/sidekick/internal/parser/disco.go, internal/sidekick/internal/parser/disco_test.go, internal/sidekick/internal/parser/openapi.go, internal/sidekick/internal/parser/openapi_test.go, internal/sidekick/internal/parser/pagination.go, internal/sidekick/internal/parser/pagination_test.go, internal/sidekick/internal/parser/parser.go, internal/sidekick/internal/parser/protobuf.go, internal/sidekick/internal/parser/protobuf_test.go
In one API (SqlAdmin) the default field for pagination is completely
wrong:
https://github.com/googleapis/googleapis/blob/a4ded737527f57207f37ba9e9c9b44732a0eb70f/google/cloud/sql/v1/cloud_sql_instances.proto#L857-L861
We need a mechanism to override the default choice.
Part of the work for https://github.com/googleapis/google-cloud-rust/issues/3430
=> feat(sidekick): override pagination items field

internal/gitrepo/gitrepo.go, internal/gitrepo/gitrepo_test.go, internal/librarian/command.go, internal/librarian/command_test.go, internal/librarian/generate_test.go, internal/librarian/mocks_test.go, internal/librarian/release_init_test.go, system_test.go
We should avoid returning other packages types in our wrappers.
Updates: #2372
=> refactor(internal/gitrepo): remove returning status from AddAll

infra/prod/generate.yaml
Similar to https://github.com/googleapis/librarian/pull/2445
Towards https://github.com/googleapis/librarian/issues/2444
=> build: bump generate timeout to 10 hours

internal/github/github.go, internal/github/github_test.go, internal/librarian/repository.go, internal/librarian/repository_test.go, internal/librarian/tag_and_release.go
The git and github packages should be standalone and not depend on eachother. Instead the thing that uses both of them, librarian, is responsible for converting the types and whatnot.
Updates: #2372
=> refactor(internal/github): remove dep on gitrepo package

internal/sidekick/rust_publish.go
During testing I hard-coded `-dry-run` to true, eventually we need to
run for realsies.
=> fix(sidekick): real runs for `rust-publish`

internal/sidekick/internal/dart/annotate.go, internal/sidekick/internal/dart/dart.go, internal/sidekick/internal/dart/templates/lib/method.mustache
The generated methods look like this:
```dart
/// Generates a [streamed response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
/// from the model given an input `GenerateContentRequest`.
Stream<GenerateContentResponse> streamGenerateContent(
GenerateContentRequest request,
) {
final url = Uri.https(_host, '/v1/${request.model}:streamGenerateContent');
return _client
.postStreaming(url, body: request)
.map(GenerateContentResponse.fromJson);
}
```
=> feat: Generate methods that use server-side streaming

internal/conventionalcommits/conventional_commits.go, internal/conventionalcommits/conventional_commits_test.go
Footer with repeated keys is not supported with current implementation, this fix let the first value be kept instead of last. Clarify in doc comment about this limitation.
When onboarding libraries that has generation pr with owlbot and release with Librarian, [commit](https://github.com/googleapis/google-cloud-python/commit/34a7916fa58727a01a7d32c6a1adff59a351fd54), the first `Source-Link:` is useful.
Alternative is to refactor `Footer` with type `map[string][]string`. It's probably not worth it because the keys we care for Librarian are not expected to repeat. This can be added as enhancement when needed.
For #2080
=> fix(internal/conventionalcommits): keep first value for repeated footer keys
