cmd/generate/main.go
internal/generate/errors.go
internal/generate/flags.go
internal/generate/run.go

Add initial command interface for generator.

impl: cmd/generate: add initial command interface

---

containers/dotnet/MakeItSo/BuildCommand.cs
containers/dotnet/MakeItSo/CreateCommand.cs
containers/dotnet/MakeItSo/Program.cs
containers/dotnet/MakeItSo/UnknownApiBehavior.cs
containers/dotnet/MakeItSo/UpdateCommand.cs

(Rebased from main, so the commits here are just for this PR.)

feat: add Build command and unknown API behavior flags (for .NET)

---

internal/container/container.go

Add commands for the proposed container interface, which are not implemented at the moment.

internal/container: add package

---

README.md
internal/command/flags.go

fix: resolve panic on startup due to duplicate language flag declaration

---

internal/command/command.go
internal/container/container.go

- api-path is now optional
- The generator-input is provided to the container, relative to the repo
- We derive the container image name from the language (google-cloud-{lang}-generator)
- The clean/build container commands are implemented
Commit and push are still not implemented, and we may want to implement a --test flag for building. (It's already in the .NET container.)

feat: implement update-repo for generate, clean, build

---

internal/command/command.go
internal/command/flags.go
internal/container/container.go

The first commit from this PR is from #43 - this PR will be a single commit once that's merged.

feat: Implement the configure command

---

internal/container/container.go

There's no need to initialize with an empty array and then append.
Fixes #48.

chore: Improve array initialization

---

internal/command/command.go
internal/command/flags.go

feat: Allow the language container image to specified on the commandline

---

internal/command/command.go
internal/command/flags.go

feat: Add a repo-root flag for configure, and make api-root optional

---

.kokoro/continuous.cfg
.kokoro/presubmit.cfg

Apologies for missing these before...

fix: Fix Kokoro paths to shell scripts

---

internal/container/container.go

This means the containers will need to support being run in this fashion (i.e. not depend on root access) but the big advantage is that any files written by the container will be owned by the user - so can easily be cleaned up.
(This also removes any need to have "git safe" directories configured due to user mismatches, although we're hoping that won't be relevant anyway.)
Fixes #81.

feat: Run docker as the current user, rather than as root

---

internal/command/command.go
internal/command/createreleasepr.go
internal/command/flags.go
internal/command/updateapis.go
internal/gitrepo/gitrepo.go

(This is best reviewed one commit at a time.)

feat: improve git interactions

---

internal/command/command.go
internal/command/configure.go
internal/command/createreleasepr.go
internal/command/updateapis.go
internal/command/updateimagetag.go
internal/gitrepo/gitrepo.go

this adds text to release PR if an error occurs when trying to generate any library, it also adds the do-not-merge label
example 
https://github.com/ldetmer/google-cloud-dotnet/pull/84

chore: add handling of errors when creating a release PR

---

internal/command/command.go

(Also reorder the way the flags are specified just for consistency.)

feat: Add -work-root flag for create-release-pr

---

internal/command/createreleasepr.go
internal/gitrepo/gitrepo.go

feat: Handle different create-release-pr scenarios appropriately

---

internal/command/command.go
internal/command/configure.go
internal/command/flags.go
internal/command/generate.go
internal/command/updateapis.go
internal/command/updateimagetag.go

This also refactors the configure code for consistency.

feat: remove output flag to simplify things

---

internal/command/command.go
internal/command/createreleasepr.go
internal/command/flags.go
internal/utils/fileutils.go

additionally add the integration tests to release-please command

feature: add storage of env vars to file in release-please command

---

.louhi/check_pr_status.go

this will be called directly from louhi to check the release PR status

chore: create script louhi can use to check if PR is merged mergable

---

internal/command/command.go
internal/command/configure.go
internal/command/createreleasepr.go
internal/command/generate.go
internal/command/release.go
internal/command/updateapis.go
internal/command/updateimagetag.go
internal/container/config.go
internal/container/container.go
internal/container/environment.go

This allows us to use just that struct (potentially adding more to it) whenever we want to make a container call.

refactor: Combine elements of container configuration in one struct

---

internal/command/updateapis.go

We need each iteration (one per library) to "see" any changes to the generator-input, for consistency. (This should only affect things like "Here's a list of APIs that have been generated.")
Fixes b/414823371

fix: Copy generator-input on each iteration of update-apis

---

internal/command/release.go

- We were previously using strings.HasPrefix the wrong way round (so the "Librarian-Release" metadata was persisted in the release notes)
- We really don't need the release title to include "Release"
- The first two lines of the commit message are redundant given the title
Fixes b/414940866

feat: Improve appearance of GitHub release

---

internal/command/mergereleasepr.go

feat: Log progress when merging release PRs

---

internal/command/createreleasepr.go
internal/command/flags.go

Also adds a -library-version flag to allow that to be forced at the same time.
It's worth reviewing one commit at a time.
Fixes b/416181133

feat: Always create a release PR when library-id is specified 

---

internal/command/command.go
internal/command/createreleaseartifacts.go
internal/command/flags.go
internal/command/publishreleaseartifacts.go
internal/utils/fileutils.go

This will require changing our release scripts.

feat: separate release into create-release-artifacts and publish-release-artifacts

---

.louhi/check_if_gob_is_synced.go
.louhi/check_pr_status.go

this will be used in release flow to ensure release commit has synced before moving forward to actual release

feat: Add script for louhi flow to check if a commit has sync to gerrit repo (GOB)

---

.louhi/check_if_gob_is_synced.go
.louhi/check_pr_status.go

this is simpler than trying to pass the data between to steps in louhi

fix: add logic to lookup release PR commit as part of gob sync script

---

internal/gitrepo/gitrepo.go

If the release ID is missing, this means going all the way back to the start of the commit history - but that's an error condition anyway.

feat: Don't assume HEAD is at the start of a release PR

---

internal/command/mergereleasepr.go

- Handle a closed PR by waiting for a minute, then failing if it's still closed
- Add more diagnostics to approvals
- Allow approval for CONTRIBUTOR or COLLABORATOR to count

feat: Improvements to merge-release-pr

---

internal/command/configure.go
internal/command/createreleasepr.go
internal/command/generate.go
internal/command/updateapis.go
internal/command/updateimagetag.go

Move execution steps into separate helper functions to improve readability for each command, particularly on pkg.go.dev.

impl(internal/command): move execute logic to separate functions

---

internal/command/command.go
internal/command/configure.go
internal/command/createreleaseartifacts.go
internal/command/createreleasepr.go
internal/command/generate.go
internal/command/mergereleasepr.go
internal/command/publishreleaseartifacts.go
internal/command/updateapis.go
internal/command/updateimagetag.go
internal/librarian/librarian.go

Replace command.RunCommand with the new Command.Run, and delete all unused code.
For #194

impl(internal/command): use Command.Run

---

generate-proto.sh
proto/README.md

docs: Document the purpose of generate-proto.sh and the protos

---

.github/ISSUE_TEMPLATE/blank-issue.md

Fixes #187 - or at least attempts to.

chore: create a single blank issue template

---

internal/librarian/updateapis.go

Towards #237
This PR only documents a single command, so that we can discuss formatting, detail level etc. Once we're comfortable with that, I expect to be able to create one PR to document all the other commands.

docs(internal/librarian): initial usage help for update-apis

---

.github/ISSUE_TEMPLATE/blank-issue.md
.github/ISSUE_TEMPLATE/config.yml

Fixes #187 (at least that's the hope)

chore: attempt to streamline the issue templates further

---

internal/librarian/configure.go
internal/librarian/createreleaseartifacts.go
internal/librarian/createreleasepr.go
internal/librarian/generate.go
internal/librarian/mergereleasepr.go
internal/librarian/publishreleaseartifacts.go
internal/librarian/updateapis.go
internal/librarian/updateimagetag.go
internal/librarian/version.go

docs(internal/librarian): Provide descriptions for all commands

---

CONTRIBUTING.md
doc/contributor-guide.md

There's definitely more to do here, but I've run out of time for today. I'm happy for us to merge as-is (if the guidance seems okay) or wait until it's more complete.
I haven't yet checked which issues are addressed by this PR. (And one thing I want to add is how to mark an issue as fixed in a comment...)

docs: first pass at more detailed contributor guidance

---

internal/container/config.go
internal/container/container.go
internal/container/environment.go
internal/librarian/configure.go
internal/librarian/createreleaseartifacts.go
internal/librarian/createreleasepr.go
internal/librarian/generate.go
internal/librarian/publishreleaseartifacts.go
internal/librarian/updateapis.go
internal/librarian/updateimagetag.go

refactor: refactor container package for testability

---

internal/gitrepo/gitrepo.go
internal/librarian/clone.go
internal/librarian/command.go
internal/librarian/configure.go
internal/librarian/createreleaseartifacts.go
internal/librarian/createreleasepr.go
internal/librarian/pullrequest.go
internal/librarian/updateapis.go
internal/librarian/updateimagetag.go

I consolidated the three factory methods to with with some configuration.
Updates: #333

refactor(internal/gitrepo): move to client model with methods

---

CONTRIBUTING.md

Fixes https://github.com/googleapis/librarian/pull/456#discussion_r2159207418

fix: adjust wording for CONTRIBUTING.md

---

internal/container/config.go
internal/container/container.go
internal/librarian/command.go
internal/librarian/publishreleaseartifacts.go

fix(internal/container): rename ContainerConfig to Docker

---

internal/githubrepo/githubrepo.go
internal/librarian/commitmessage.go
internal/librarian/configure.go
internal/librarian/createreleasepr.go
internal/librarian/flags.go
internal/librarian/mergereleasepr.go
internal/librarian/updateimagetag.go

(One TODO has just been removed, as I now understand the reason behind it, and we can wait for refactoring to see if the functions should become a method.)
Fixes #490

chore(all): add links to all TODOs

---

internal/gitrepo/gitrepo.go

fix(internal/gitrepo): define constants for default user name and email

---

doc/onboarding.md

Fix whitespace in "Helpful Links" section.

doc: fix formatting in onboarding.md

---

CONTRIBUTING.md

Add information outlining expectations for reviewing pull requests and link to `user-review-requested:@me` dashboard.
Fixes https://github.com/googleapis/librarian/issues/593

doc(CONTRIBUTING.md): add code review guidelines

---

internal/secrets/secrets.go
internal/secrets/secrets_test.go

Follow-up to #607
Towards #531

test: add secrets.Get test with mock interface

---

all_test.go
internal/docker/docker.go
internal/docker/environment.go
internal/githubrepo/githubrepo.go
internal/librarian/updateapis.go
internal/librarian/updateimagetag.go
internal/secrets/secrets.go

Some errors were ignored which are now handled.

fix(all): handle missing errors

---

.gitignore

Add .vscode to .gitignore to make local dev smoother

chore: add vscode setting/config folder to gitignore

---

.golangci.yaml
internal/librarian/generate.go

chore(golangci-lint): fix issues for contextcheck and turn on #647

---

.golangci.yaml

chore(lint): enabled containedctx linter and fixed errors

---

CONTRIBUTING.md

This adds instructions for reverting pull requests using the GitHub UI.
Fixes: #320.

docs(contributing): create standard process for reverting PRs

---

internal/docker/docker.go
internal/docker/environment.go
internal/gitrepo/gitrepo.go
internal/librarian/command.go
internal/librarian/configure.go
internal/librarian/createreleaseartifacts.go
internal/librarian/createreleasepr.go
internal/librarian/generate.go
internal/librarian/mergereleasepr.go
internal/librarian/publishreleaseartifacts.go
internal/librarian/pullrequest.go
internal/librarian/updateapis.go
internal/librarian/updateimagetag.go

refactor(all): migrate slog calls to idiomatic structured logging

---

internal/config/config.go
internal/librarian/flags.go

fix(internal/cli): rename flag work-root to output

---

internal/librarian/flags.go
internal/librarian/generate.go

For https://github.com/googleapis/librarian/pull/686

fix(internal/librarian): rename flagAPIPath to flagAPI

---

Dockerfile

chore(all): update go version to 1.24.4

---

doc/architecture.md
doc/container-contract.md

docs: add initial architecture and container contract docs

---

CONTRIBUTING.md

docs(contributing): add info about retriggering multi-approvers check

---

all_test.go
cmd/librarian/main.go
internal/librarian/command.go
internal/librarian/commitmessage.go
internal/librarian/createreleaseartifacts.go
internal/librarian/flags.go
internal/librarian/generate.go
internal/librarian/pullrequest.go

This change fixes existing lint issues in project.  
fix for: https://github.com/googleapis/librarian/issues/693

chore(lint): fix godoc linter errors and turn on godoc linter test

---

all_test.go

chore(all): exclude .idea from header tests

---

internal/librarian/generate_test.go

This should be enough tests for the generate package for now. We can improve coverage more in the future, but that will take more abstracting and reworking the gitrepo package. Will wait to make those changes until the codebase settles more.
Fixes: #753

test(internal/librarian): add more tests for generate

---

internal/docker/environment.go
internal/secrets/secrets.go
internal/secrets/secrets_test.go

refactor(internal/secrets): setup similar client model used in other pkgs

---

internal/cli/cli_test.go
internal/cli/version.go
internal/cli/version_test.go
internal/config/state_test.go
internal/github/github_test.go

Backfilling tests across many package to help increase our coverage.
Updates: #744

test: backfill tests

---

GEMINI.md

I have been trying to lean into using gemini more in my personal devflow. I think adding this file could help others ground thier environment for better results.

chore: add GEMINI.md

---

internal/docker/docker.go
internal/docker/docker_test.go

Remove `generate-request.json` and `build-request.json` after running docker container.
Fixes: #869

chore(internal/docker): remove request files

---

internal/config/config.go
internal/config/config_test.go
internal/librarian/flags.go

make pushConfig default to empty string
fix: #724

fix: make pushConfig default to empty string

---

codecov.yml

chore: lock in 80% coverage

---

internal/sidekick/internal/api/deprecated_test.go

test(sidekick): add tests for `HasDeprecatedEntities`

---

internal/sidekick/internal/api/model_test.go

test(sidekick): missing tests for `api` package

---

internal/sidekick/internal/rust/annotate_test.go
internal/sidekick/internal/rust/codec.go

test(sidekick): missing tests for `rust` package

---

internal/sidekick/internal/language/codec_test.go

test(sidekick): missing tests in `language` package

---

codecov.yml

chore(all): drop target test coverage

---

internal/config/global_config.go
internal/config/global_config_test.go

feat: add a global config

---

doc/language-onboarding.md

Some last minute changes to the release design.

doc: update language onboarding guide

---

internal/librarian/init.go
internal/librarian/init_test.go

Also put some more details in the error for debugging.

test(internal/librarian): fix validation test

---

internal/librarian/flags.go
internal/librarian/generate.go

fix: generate command should parse the -push flag

---

infra/test/token-access-test.yaml

The file path was updated in https://github.com/googleapis/librarian/pull/1687

ci: update repository.yaml path in token validation test

---

internal/config/config_test.go

Add test cases in `internal/config` package.

test: improve test coverage

---

generate_e2e_test.go
internal/librarian/generate.go
internal/librarian/generate_test.go

fix(internal/librarian): support local language repos better

---

infra/prod/publish-release.yaml

https://github.com/googleapis/librarian/issues/1609
https://github.com/googleapis/librarian/issues/1610

feat: Add Publish release GCB job config

---

internal/librarian/release_init.go
internal/librarian/release_init_test.go

fix: setup global config in init docker command

---

infra/prod/generate-worker.yaml
infra/prod/generate.yaml
internal/automation/cli.go
internal/automation/cli_test.go
internal/automation/trigger.go
internal/automation/trigger_test.go

build: add -build flag to generate command

---

internal/config/config.go
internal/librarian/command.go
internal/librarian/command_test.go
internal/librarian/flags.go
internal/librarian/release_init.go
internal/librarian/release_init_test.go

feat: implement `commit` flag for release init

---

internal/librarian/release_init.go
internal/librarian/release_init_test.go

fix: ignore version override if library flag is not specified

---

internal/docker/docker.go
internal/docker/docker_test.go

fix(librarian): don't pass undocumented flags

---

internal/librarian/flags.go

docs: update help text for library flag

---

internal/librarian/generate_test.go
internal/librarian/release_please_lite.go

fix: skip fetching commits if last generated commit is empty

---

internal/librarian/release_init.go

chore: add output flag to release init command

---

generate_e2e_test.go

test: add e2e test for clean and copy functions

---

infra/prod/stage-release.yaml

build: need the entire release repo for a release init command

---

infra/prod/stage-release.yaml

build: configure user name/email for git

---

internal/github/github.go
internal/github/github_test.go
internal/librarian/command.go

fix(librarian): support SSH remotes

---

internal/librarian/flags.go

docs(librarian): fix repo flag formatting

---

internal/librarian/generate.go

feat(internal/librarian): log generation statistics on completion

---

internal/librarian/release_notes.go
internal/librarian/release_notes_test.go

Created release pull request in https://github.com/googleapis/librarian/pull/1966
Fixes #1957

fix: format release note correctly for multiple same category commits

---

internal/librarian/generate.go

fix(internal/librarian): commit the right repo in generate

---

all_test.go

test: ignore .txt files for license headers

---

internal/sidekick/internal/rust_release/bump_versions_test.go
internal/sidekick/internal/rust_release/last_tag.go
internal/sidekick/internal/rust_release/last_tag_test.go
internal/sidekick/internal/rust_release/preflight_test.go

impl(sidekick): get last release tag

---

infra/prod/stage-release-worker.yaml
internal/automation/cli.go
internal/automation/cli_test.go
internal/automation/cloudbuild_test.go
internal/automation/trigger.go
internal/automation/trigger_test.go

Stage release job with forceRun flag.
By default Stage release job will only be run on odd weeks, and forceRun flag is False.
If forceRun is True, Stage release job can be run on even weeks.
Check cloudBuild trigger with triggersRun variable
https://github.com/googleapis/librarian/issues/2060

feat: Stage release with forceRun flag. Check cloudBuild trigger with triggersRun variable

---

internal/librarian/command.go

Remove unused commandRunner.cfg field.

refactor(internal/librarian): remove cfg from commandRunner

---

doc/config-schema.md
doc/language-onboarding.md
doc/state-schema.md

docs: add config.yaml schema doc page

---

internal/github/github.go
system_test.go

Towards #300 
Usage:
```bash
TEST_GITHUB_TOKEN=<your-token> \
TEST_GITHUB_REPOSITORY=<target-repo> \
go test -v system_test.go
```
If you do not provide a `TEST_GITHUB_TOKEN`, none of the tests run. If you do not provide a `TEST_GITHUB_REPOSITORY` repository, then the pull request creation/edit tests do not run.

test: add conditional GitHub integration tests

---

e2e_test.go
internal/librarian/tag_and_release.go

Updates the end-to-end test for the 'release tag-and-release' command to align with the refactoring introduced in commit 2807adf.
The refactoring removed the command's dependency on a local repository clone, causing the existing e2e test to fail as it was still based on a local git setup. The command now fetches the state.yaml file directly from the GitHub API.
This change updates the test by:
- Removing the unnecessary local git repository setup.
- Modifying the mock HTTP server to correctly simulate the multi-step API process used by the go-github client to download a file (directory listing followed by content download).
- Updating the 'newTagAndReleaseRunner' to correctly use the 'github-api-endpoint' flag, ensuring the client is properly directed to the mock server during tests.
Part …

fix(testing): align tag-and-release e2e test with API workflow

---

internal/librarian/generate.go
internal/librarian/generate_test.go

fixes: https://github.com/googleapis/librarian/issues/2238

fix: read api dir from temp folder

---

internal/gitrepo/gitrepo.go
internal/gitrepo/gitrepo_test.go

feat: clean untracked files

---

internal/sidekick/internal/parser/discovery/uritemplate.go
internal/sidekick/internal/parser/discovery/uritemplate_test.go

fix(sidekick): URI templates need matchers too

---

internal/sidekick/internal/parser/discovery/methods.go
internal/sidekick/internal/parser/discovery/methods_test.go

impl(sidekick): add methods to state

---

internal/librarian/doc.go
internal/librarian/flags.go
internal/librarian/librarian.go
internal/librarian/librarian_test.go

Adds -v flag to the CLI that sets the logging level to debug for each command
Fixes #2148

feat(internal/librarian): add flag to configure verbose logging

---

internal/github/github.go
internal/librarian/command.go
internal/librarian/command_test.go
internal/librarian/generate.go
internal/librarian/mocks_test.go

feat: add a comment to generation PR if generation has a failure

---

internal/config/config.go
internal/config/config_test.go

Creating a temporary directory based on a timestamp is inherently racy.
Use the standard functions to create temporary directories, and relax
the tests to check for what matters.

fix(config): race condition in createWorkRoot()

---

internal/sidekick/internal/parser/discovery/message_fields.go
internal/sidekick/internal/parser/discovery/message_fields_test.go

feat(sidekick): discovery doc arrays

---

internal/sidekick/internal/api/apitest/apitest.go
internal/sidekick/internal/parser/discovery/enum.go
internal/sidekick/internal/parser/discovery/enum_field_test.go
internal/sidekick/internal/parser/discovery/message_fields.go

feat(sidekick): parse discovery doc enums

---

internal/sidekick/internal/parser/discovery/enum.go
internal/sidekick/internal/parser/discovery/enum_field_test.go

fix(sidekick): missing field for discovery enums

---

internal/docker/docker.go
internal/librarian/state.go

feat(librarian): add container req/resp debug logging

---

internal/sidekick/internal/parser/discovery/map_field.go
internal/sidekick/internal/parser/discovery/map_field_test.go
internal/sidekick/internal/parser/discovery/message_fields.go

feat(sidekick): maps for discovery docs

---

internal/librarian/command.go
internal/librarian/command_test.go
internal/librarian/generate.go
internal/librarian/release_init.go

feat: write pr-body.txt to the work root when not pushing

---

internal/sidekick/internal/parser/discovery/inline_object_field.go
internal/sidekick/internal/parser/discovery/inline_object_field_test.go
internal/sidekick/internal/parser/discovery/message_fields.go

feat(sidekick): inline messages in discovery docs

---

internal/sidekick/internal/parser/disco_test.go
internal/sidekick/internal/parser/discovery/discovery.go
internal/sidekick/internal/parser/discovery/discovery_test.go
internal/sidekick/internal/parser/discovery/enum.go
internal/sidekick/internal/parser/discovery/enum_field_test.go
internal/sidekick/internal/parser/discovery/inline_object_field.go
internal/sidekick/internal/parser/discovery/inline_object_field_test.go
internal/sidekick/internal/parser/discovery/map_field.go
internal/sidekick/internal/parser/discovery/map_field_test.go
internal/sidekick/internal/parser/discovery/message_fields.go
internal/sidekick/internal/parser/discovery/message_fields_test.go
internal/sidekick/internal/parser/discovery/methods.go
internal/sidekick/internal/parser/discovery/methods_test.go
internal/sidekick/internal/parser/discovery/services.go
internal/sidekick/internal/parser/discovery/services_test.go

feat(sidekick): deprecated elements in discovery docs

---

internal/sidekick/internal/parser/discovery/discovery_test.go
internal/sidekick/internal/parser/discovery/enum_field_test.go
internal/sidekick/internal/parser/discovery/inline_object_field_test.go
internal/sidekick/internal/parser/discovery/message_fields.go
internal/sidekick/internal/parser/discovery/message_fields_test.go

feat(sidekick): optional singular fields in discovery

---

internal/docker/docker.go
internal/docker/docker_test.go
internal/librarian/generate.go
internal/librarian/generate_test.go

feat: include source root in configure request

---

infra/prod/generate.yaml

build: bump generate timeout to 6 hours

---

internal/github/github.go
internal/github/github_test.go

fix: nil check for github.NewClient

---

internal/sidekick/internal/config/config.go
internal/sidekick/internal/config/config_test.go
internal/sidekick/internal/config/update_root_config.go
internal/sidekick/internal/config/update_root_config_test.go

refactor(sidekick): split update root config

---

internal/librarian/state.go
internal/librarian/state_test.go

feat: sort library state when writing to `state.yaml`
